# Generated by Django 4.1.5 on 2023-01-25 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='flag',
            field=models.CharField(choices=[('New', 'New'), ('Sale', 'Sales'), ('Feature', 'Feature')], max_length=10, verbose_name='flag'),
        ),
    ]
