# Generated by Django 4.1.5 on 2023-02-02 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantitiy',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='flag',
            field=models.CharField(choices=[('New', 'New'), ('Sale', 'Sales'), ('Feature', 'Feature')], max_length=10, verbose_name='flag'),
        ),
    ]
