# Generated by Django 4.1.5 on 2023-02-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_rename_quantitiy_product_quantity_alter_product_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='flag',
            field=models.CharField(choices=[('Feature', 'Feature'), ('New', 'New'), ('Sale', 'Sale')], max_length=10, verbose_name='flag'),
        ),
    ]
